name             'testhome'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures testhome'
long_description 'Installs/Configures testhome'
version          '0.1.0'
